### ISSUE TITLE
Empty Attendance Record

### ISSUE THREAD

**Issue by JeffGepiga** [raihanafroz/zkteco#20]
![image](https://user-images.githubusercontent.com/51604875/206654113-351899d9-b690-4e44-a902-6db82940433a.png)

Im getting this result, any ideas?

**Comment by JeffGepiga** [comment]
anyone encountered this? our Biometric Device has 70k records, and half of the records were like this, and when I generate it using USB, it shows the correct data, I think the issue is transforming or fetching data from the biometric to php array

**Comment by Duddy-Satrianugraha** [comment]
i use:

```$zk = new ZKTeco('192.168.1.201');
if($zk->connect() ){
  $data = $zk->getAttendance(); 
$zk->disconnect();   
} 
```
then 

```
var_dump($data);
die();
```
if still empty chek machine version

**Comment by JeffGepiga** [comment]
> i use:
> 
> ```
> if($zk->connect() ){
>   $data = $zk->getAttendance(); 
> $zk->disconnect();   
> } 
> ```
> 
> then
> 
> ```
> var_dump($data);
> die();
> ```
> 
> if still empty chek machine version

Hi, yes I can connect and disconnect with the device, and upon exploring for a couple of days and did some testing, I think this is OS bug with the device because we cannot also clear it from the device itself, what we did is we created a backup of the fingerprint and employee data and execute a factory reset and restored the backup.
