### ISSUE TITLE
Maximum execution time of 60 seconds exceeded

### ISSUE THREAD

**Issue by Fajendagba** [raihanafroz/zkteco#9]
So I've installed the library in my Laravel project and also have a K40 device.
I want to test the device connection with the library ( I used the $zk->connect () method, but it won't output anything, rather it would only slow down and finally return the error "Maximum execution time of 60 seconds exceeded".

Pls anyone who knows this fix should help 🥺

**Comment by trungkien10290** [comment]
> So I've installed the library in my Laravel project and also have a K4

The same issue! are u have any solutions?

**Comment by raihanafroz** [comment]
Good day dear,

Please add "ini_set('max_execution_time', 300);" line before calling "$zk
->connect()" method and wait for the response.

Thank you.
